name: Study GitHub action

on:
  push: 
    branches:
      - dev
  
jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Chao hoi
        run: echo "Workflow dang chay thanh cong!"

      - name: Kiem tra thoi gian
        run: date
      
      - name: Kiem tra cau hinh may ao
        run: |
          echo "Ten he dieu hanh:"
          lsb_release -a
          echo "Phien ban Python co san:"
          python3 --version